### ISSUE TITLE
Network Vrtx file output written as shapefile into Toolbox folder, rather than geodatabase

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#46]
So in this version of arcGNAT (2.2), it looks like Build Network Topology has gone back to writing the NetworkVrtx nodes out into a shapefile that goes into the Toolbox folder, rather than into the Preprocess geodatabase with the _run01 and Stream Network table output. Any way we can switch it back to writing it into the geodatabase? (It had been fixed several versions ago and was doing this correctly up to the last version I've been using, arcGNAT_2.1.12) 

Thanks.

**Comment by jesselangdon** [comment]
There was an issue with how the NetworkVrtx file was being named.  It was initially set up to export to a fiel geodatabase (with no extension), but it was showing up in the tool folder by default (not sure why).

Fixed with this commit: https://github.com/Riverscapes/arcGNAT/commit/31215d00015c0fafd79f2fb948516f32031c7b89
