### ISSUE TITLE
It doesn't look like arcGNAT is using latest version of Riverscapes Jekyll Theme

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/arcGNAT#86]
Hey @philipbaileynar,
When you get a chance, can you do a quick update to arcGNAT so that it is using the latest https://github.com/Riverscapes/riverscapes-jekyll-theme/?

Thanks,
JOe

**Comment by philipbaileynar** [comment]
1. @joewheaton I can confirm that the site is using the latest integrated theme. 
1. This was a "plain white" Jekyll site before I implemented the integrated theme back in the fall of 2019. It had some legacy contents from Jesse (e.g. side bar markdown file) that I have now removed.
1. Matt also fixed a bug in the way the folders were rendering spaces. All folders must now use underscores instead of spaces.
1. There was also a legacy `_site` folder that someone had accidentally pushed after serving the site locally.

All the above issues are now fixed.
